import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
} from "drizzle-orm/pg-core";
import { organization } from "./organization";
import { cardTestingTrackers } from "./cardTestingTrackers";
import { InferInsertModel, InferSelectModel, relations } from "drizzle-orm";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

// ==========================================
// TYPES FOR JSONB FIELDS
// ==========================================

export interface FraudFactor {
  type: string; // geographic_mismatch, velocity_abuse, card_testing, etc.
  weight: number; // points added/subtracted
  description: string; // human-readable explanation
  severity: "low" | "medium" | "high";
}

export interface DetectionContext {
  // Location data
  ipAddress?: string;
  ipCountry?: string;
  ipRegion?: string;
  ipCity?: string;

  // Card data
  cardLast4?: string;
  cardBrand?: string; // visa, mastercard, amex
  cardCountry?: string;
  cardFingerprint?: string; // hashed card identifier
  cardFunding?: string; // credit, debit, prepaid

  // Device data
  deviceFingerprint?: string;
  userAgent?: string;
  deviceType?: string; // mobile, desktop, tablet
  browser?: string;

  // Velocity metrics
  velocity?: {
    attemptsLastHour: number;
    attemptsLastDay: number;
    uniqueCardsUsed: number;
    rapidAttempts: boolean;
  };

  // Customer trust data (snapshot at time of transaction)
  customer?: {
    id?: string;
    accountAge?: number; // days
    totalPurchases?: number;
    totalSpent?: number;
    avgPurchaseAmount?: number;
    disputeHistory?: number;
    refundHistory?: number;
    trustScore?: number; // 0-100
    tier?: string; // blocked, suspicious, new, trusted, vip
    whitelisted?: boolean;
  };

  // Transaction patterns
  transactionPatterns?: {
    unusualAmount?: boolean;
    unusualTime?: boolean; // e.g., 3am
    newDevice?: boolean;
    newLocation?: boolean;
  };
}

// ==========================================
// FRAUD DETECTIONS TABLE
// ==========================================
export const fraudDetections = pgTable(
  "fraud_detections",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),

    // Stripe Transaction Reference
    paymentIntentId: text("payment_intent_id").notNull().unique(),
    stripeChargeId: text("stripe_charge_id"),
    stripeInvoiceId: text("stripe_invoice_id"),
    stripeCustomerId: text("stripe_customer_id"), // May be null for one-off payments

    // Card Testing Tracker Reference (if this transaction is part of a card testing attempt)
    cardTestingTrackerId: text("card_testing_tracker_id").references(
      () => cardTestingTrackers.id,
      { onDelete: "set null" }
    ),

    // Transaction Details
    amount: integer("amount").notNull(), // in cents
    currency: text("currency").default("eur").notNull(),
    customerEmail: text("customer_email"),
    customerName: text("customer_name"),
    description: text("description"),

    // Detection Results (Rules Engine)
    riskScore: integer("risk_score").notNull(), // 0-100
    decision: text("decision").notNull(), // ALLOW, BLOCK, REVIEW
    confidence: text("confidence").notNull(), // low, medium, high

    // Factors that influenced the decision
    factors: jsonb("factors").$type<FraudFactor[]>().notNull().default([]),

    // Signals from detection engine
    signals: jsonb("signals").notNull().default({}),

    // Agents used for analysis
    agentsUsed: text("agents_used").array().notNull().default([]),

    // AI Explanation (generated by Mastra)
    aiExplanation: text("ai_explanation"),
    aiModel: text("ai_model"), // gpt-4o-mini, gpt-4o, etc.
    aiGeneratedAt: timestamp("ai_generated_at"),
    aiTokensUsed: integer("ai_tokens_used"),
    aiLatencyMs: integer("ai_latency_ms"),

    // Detection Context (used for decision)
    detectionContext: jsonb("detection_context").$type<DetectionContext>(),

    // Merchant Actions (feedback loop)
    merchantOverride: text("merchant_override"), // allowed, blocked, null
    overrideReason: text("override_reason"),
    overrideNote: text("override_note"),
    overrideAt: timestamp("override_at"),

    // Actual Outcome (for ML improvement)
    actualOutcome: text("actual_outcome"), // fraud_confirmed, legitimate, chargeback, unknown
    outcomeConfirmedAt: timestamp("outcome_confirmed_at"),
    outcomeNote: text("outcome_note"),

    // Chargeback tracking
    chargebackReceived: boolean("chargeback_received").default(false).notNull(),
    chargebackAmount: integer("chargeback_amount"),
    chargebackReason: text("chargeback_reason"),
    chargebackReceivedAt: timestamp("chargeback_received_at"),

    // Action taken
    blocked: boolean("blocked").default(false).notNull(),
    actionTaken: text("action_taken"), // none, blocked, refunded, flagged
    actionTakenAt: timestamp("action_taken_at"),
    refundId: text("refund_id"),

    // Timestamps
    detectedAt: timestamp("detected_at").defaultNow().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("fraud_detections_organization_idx").on(table.organizationId),
    index("fraud_detections_decision_idx").on(table.decision),
    index("fraud_detections_risk_score_idx").on(table.riskScore),
    index("fraud_detections_customer_email_idx").on(table.customerEmail),
    index("fraud_detections_stripe_customer_idx").on(table.stripeCustomerId),
    index("fraud_detections_detected_at_idx").on(table.detectedAt),
    index("fraud_detections_payment_intent_idx").on(table.paymentIntentId),
    index("fraud_detections_card_testing_tracker_idx").on(
      table.cardTestingTrackerId
    ),
    // Composite indexes for common queries
    index("fraud_detections_org_decision_idx").on(
      table.organizationId,
      table.decision
    ),
    index("fraud_detections_org_date_idx").on(
      table.organizationId,
      table.detectedAt
    ),
  ]
);

// ==========================================
// RELATIONS
// ==========================================
export const fraudDetectionsRelations = relations(
  fraudDetections,
  ({ one }) => ({
    organization: one(organization, {
      fields: [fraudDetections.organizationId],
      references: [organization.id],
    }),
    cardTestingTracker: one(cardTestingTrackers, {
      fields: [fraudDetections.cardTestingTrackerId],
      references: [cardTestingTrackers.id],
    }),
  })
);

// ==========================================
// TYPES & SCHEMAS
// ==========================================
export type FraudDetection = InferSelectModel<typeof fraudDetections>;
export type NewFraudDetection = InferInsertModel<typeof fraudDetections>;

export const fraudDetectionsInsertSchema = createInsertSchema(fraudDetections);
export const fraudDetectionsSelectSchema = createSelectSchema(fraudDetections);
